/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ForecastExamination: typeof import('./src/components/ENSO/ForecastExamination.vue')['default']
    ForecastResult: typeof import('./src/components/ENSO/ForecastResult.vue')['default']
    GlobalWeatherForecastResult: typeof import('./src/components/GlobalWeather/GlobalWeatherForecastResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
